config/routes.rb
Rails.application.routes.draw do
 root 'games#index'
 resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)
    if @game.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def game_params
    params.require(:game).permit(:title, :description)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1>WendyGo Games Studios</h1>

<%= @games.each do |game| %>
  <%= game.title %>
  <%= game.description %>
<% end %>

app/views/games/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">

  <h1>New Game</h1>

  <%= simple_form_for @game do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.submit "Post!", class: 'my-btn' %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wendygo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Wendygo', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item">
              <%= link_to new_game_path, class: 'nav-link' do %>
                <i class="fa fa-plus-circle"></i>
                New Game
              <% end %>
            </li>
          </ul>
        </div>
      </nav>

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>


    
    <%= yield %>
    </div>

    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-3">
            <b>Contact</b>
            <br />
            zoebkramer@gmail.com
            <br />
            San Francisco CA, 94103
          </div>
          <div class="col-12 col-sm-3">
            <b>Social</b>
            <br />
            <%= link_to 'https://github.com/ZoeBKramer' do %>
              <span class="fa fa-github-square fa-2x social-button"></span>
            <% end %>
            <%= link_to 'https://www.linkedin.com/in/zoe-kramer-a68640162/' do %>
                <span class="fa fa-linkedin-square fa-2x social-button"></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>